/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */
package  parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MODIFICADOR = 5;
  /** RegularExpression Id. */
  int CLASE = 6;
  /** RegularExpression Id. */
  int TIPO = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int SI = 9;
  /** RegularExpression Id. */
  int MIENTTRAS = 10;
  /** RegularExpression Id. */
  int PARENTESIS_IZQ = 11;
  /** RegularExpression Id. */
  int PARENTESIS_DER = 12;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 13;
  /** RegularExpression Id. */
  int CORCHETE_DER = 14;
  /** RegularExpression Id. */
  int PUNTO_Y_COMA = 15;
  /** RegularExpression Id. */
  int COMA = 16;
  /** RegularExpression Id. */
  int PUNTO = 17;
  /** RegularExpression Id. */
  int ASIGNACION = 18;
  /** RegularExpression Id. */
  int COMPARADORES = 19;
  /** RegularExpression Id. */
  int MAS = 20;
  /** RegularExpression Id. */
  int MENOS = 21;
  /** RegularExpression Id. */
  int MULTIPLICACION = 22;
  /** RegularExpression Id. */
  int LITERAL_ENTERA = 23;
  /** RegularExpression Id. */
  int LITERAL_BOOLEANA = 24;
  /** RegularExpression Id. */
  int LITERAL_CADENA = 25;
  /** RegularExpression Id. */
  int LITERAL_DOBLE = 26;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<MODIFICADOR>",
    "\"class\"",
    "<TIPO>",
    "\"void\"",
    "\"if\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "<COMPARADORES>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<LITERAL_ENTERA>",
    "<LITERAL_BOOLEANA>",
    "<LITERAL_CADENA>",
    "<LITERAL_DOBLE>",
    "<IDENTIFICADOR>",
  };

}
